# Generated by Django 5.1.5 on 2026-09-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='scheduled_days',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='scheduled_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='scheduled_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
